### PR TITLE
Fixes #206 and #224

### LINKED ISSUE #206: Filter statisticgroups endpoint by regression region status?
I think since we query statistic groups for a region based on the available equations, we'll also want to make sure that filters based on the regression region status IDs.

For example, based on the status IDs, the production services in WV only get a scenario for the depth statistics, although based on the statisticgroups endpoint it seems like there are more. 

https://streamstats.usgs.gov/nssservices/Regions/WV/Scenarios
https://streamstats.usgs.gov/nssservices/statisticgroups?regions=WV

### PR DESCRIPTION
**Pull request by harper-wavra**
Filtered GetRegressions endpoint by regression region
Filtered GetCitations endpoint by regression region
Filtered GetStatisticGroups endpoint by regression region

### CODE REVIEW

**Comment by kjacobsen16** [comment]
@harper-wavra I don't have time to pull this down and test it, but the code looks good on first glance. @amedenblik if you want, you can pull it down and do some checking to make sure it works as well as to get some good practice in. I'll leave the email for this unread so I can come back and review it if I have time with my few hours a week.

**Review by kjacobsen16 — CHANGES_REQUESTED** [review]
The "getLoggedInUser()" function for the statistic groups and regression types don't include the username like the nsscontrollerbase does. The applicable status function checks for the manager's username to see if someone is logged in, and since it's null in those cases it doesn't think anyone is logged in. You should add the username in to make sure managed users get all possible options in these endpoints (e.g. http://localhost:53813/regressiontypes?regions=Test should return the regression types used in the deprecated equations when a user is logged in, same for stat groups). Once that's working, you'll be good to go!

**Comment by harper-wavra** [comment]
@amedenblik I just push up the changes KJ requested and tested them out. So I think this should be good to go.

[Logged in StatisticGroups](https://user-images.githubusercontent.com/59063181/129947145-832a9014-2d95-484f-90bd-af6e2ac44f84.png)
[Not Logged in StatisticGroups](https://user-images.githubusercontent.com/59063181/129947174-a79cabc8-2762-4b35-b8e1-d4d10fb9221e.png)
[Not Logged in RegressionTypes](https://user-images.githubusercontent.com/59063181/129947210-1839af4c-df67-4b66-bf89-049825cd4954.png)
[Logged in RegressionTypes](https://user-images.githubusercontent.com/59063181/129947239-dbdfb560-be3d-45fd-bd21-73b41d6c0a45.png)

**Review by kjacobsen16 — APPROVED** [review]
Works well for me! 

Now you'll just need to fix those merge conflicts from the last pull request.

**Pull request merged**
