### PR TITLE
Fixes #192

### LINKED ISSUE #192: Add Unit Types and Statistic Groups to Regression Types Table
Might be on a similar vein to #94 

We can pull these from the SSDB the same way we are for the variable types (note to self: GageStatsScript on my computer)

### PR DESCRIPTION
**Pull request by harper-wavra**
Added `englishUnitTypeID`, `metricUnitTypeID` and `statisticGroupID` to `regressionTypes`.

I am able to send a:
- GET request and back name, code, description, `metricUnitTypeID`, `englishUnitTypeID`, and `statisticGroupID`.
- POST and create a regression type with all the properties.
- PUT and edit a regression type and its properties.
- DELETE and delete a regression type.

In the issue I was unsure how to "Update Shared services info for gagestats" is there more information for this somewhere?
I was also unsure what "We should replicate the variables here as well - we might need this to be send through in a few places" meant. It seems like everything is working though.

### CODE REVIEW

**Comment by kjacobsen16** [comment]
@harper-wavra what I meant by replicating the variables was that if there is an `.Include()` function that includes the full unit and statistic group types, we should do the same for the regression types, so if the variable type includes the whole unit and statistic group objects in, say, the estimate scenarios endpoint or the get variables endpoint, we should also include them in the estimate scenarios endpoint and the get regression types endpoint. You can see how the variables are doing it here: https://github.com/USGS-WiM/NSSServices/blob/dev/NSSAgent/NSSAgent.cs#L1204. The `.Include()` function is a way to include virtual properties like the unit type assigned using the unittypeids - see https://test.streamstats.usgs.gov/nssservices/variables/1 - it not only includes the metricUnitTypeID but also the full metricUnitType, which shows the name, code, etc. for the metric unit.

Also, generally if there are changes to any files in the "Shared" section of the NSSServices, you'll need to right click on the "Shared" item in Visual Studio and hit "Rebuild":
image. Then, copy the files from the `NSSServices\Shared\bin` folder into the GageStatsServices' `lib` folder. I think the "rebuild" remakes the `Shared\bin\Debug\netcoreapp3.1` folder, and publishing the NSSServices rebuilds the `Shared\bin\Release\netcoreapp3.1` folder. I think as long as you make sure the one you're copying from is updated, you can copy from either. (this should be noted elsewhere, you'll want to remember this for any time you update anything in the shared section). Once you do this, the GageStatsServices locally should have all updates you made to the Shared files, but I would double check that and make sure you're not missing other updates that may need to be done outside of the Shared section, like if there's a call in the NSSAgent that's also done in the GageStatsAgent that needs to be replicated.

I'll come back and review this pull request later.

**Comment by harper-wavra** [comment]
@kjacobsen16 I added some include functions for the regression types which seem to be working. 

I was looking at your instructions for updating the shared services for gagestats and you stated "if there are changes to any files in the "Shared" section of the NSSServices" I would need to follow those steps. It looks like there are only changes to the SharedDB section of the NSSServices, so do I still need to follow those instructions if there are changed to the SharedDB section too?

**Comment by kjacobsen16** [comment]
Yes, sorry about that - I mean anything related to "Shared", so that includes SharedDB as well.

**Comment by harper-wavra** [comment]
@kjacobsen16 
I think is now ready to be reviewed. I added the `include` function to send the whole objects, and I rebuilt the SharedDB.

Related GageStatsServices pull request: https://github.com/USGS-WiM/GageStatsServices/pull/111, which has the rebuilt files added, and the `include` function added.

**Review by kjacobsen16 — APPROVED** [review]
Great job! I left one small typo recommendation. One more recommendation - it's helpful to also include the full objects for the unit types and stat groups after a user adds or edits an object, but this is optional!

We might have issues opened in NSS already, but we'll want to also allow users in NSS to assign the metric unit type, english unit type and statistic group type for the regression types when adding or editing. There are also some other places where we might want to pull this info, such as the add scenario component - that can be used to more easily (a) filter the regression types by statistic group (in the past the filters were based on if the regression type was used in an equation assigned to a statistic group, not based on the default statistic group for that regression type), and (b) to get the unit options for the scenario they're adding. It also might be helpful to check the default units and statistic groups for regression types on equations entered in the batch upload in NSS. Note that this might cause some confusion with the filters on the NSS endpoint - since those filters are based on the usage in equations, not the assigned default values.

**Pull request merged**
